return {}
-- return {
--   {
--     "zbirenbaum/copilot.lua",
--     opts = {
--       panel = {
--         enabled = true,
--         auto_refresh = false,
--         keymap = {
--           jump_prev = "[[",
--           jump_next = "]]",
--           accept = "<CR>",
--           refresh = "gr",
--           open = "<C-CR>", -- not working
--         },
--         layout = {
--           position = "bottom", -- | top | left | right
--           ratio = 0.4,
--         },
--       },
--       suggestion = {
--         enabled = true,
--         auto_trigger = false,
--         hide_during_completion = true,
--         debounce = 75,
--         keymap = {
--           accept = "<C-l>",
--           accept_word = false,
--           accept_line = false,
--           next = "<C-]>",
--           prev = "<C-[>",
--           dismiss = "<M-]>",
--         },
--       },
--       filetypes = {
--         javascript = true,
--         typescript = true,
--         php = true,
--         yaml = true,
--         json = true,
--         sh = true,
--         dockerfile = true,
--         env = true,
--         md = true,
--         yml = true,
--         markdown = true,
--         lua = true,
--         ["*"] = false,
--       },
--       copilot_node_command = "node", -- Node.js version must be > 18.x
--       server_opts_overrides = {},
--     },
--   },
-- }
